app/models/user.rb
app/uploaders/photo_uploader.rb

Setup upload terminé afin de pouvoir faire charger un avatar à un utilisateur (gem / bundle install, model User modifié).
Ok pour vous ?

Add upload setup

---

app/models/user.rb
app/uploaders/photo_uploader.rb

Reverts Adhemarish/frozen#3
peux-tu revenir en arrière et supprimer ce merge ?
merci.

Revert "Add upload setup"

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/views/equipments/index.html.erb
app/views/shared/_navbar.html.erb

J'ai travaillé sur le front de la homepage.
J'ai ajouté le path to homepage dans le logo Frozen de la nav bar :)

updated front Homepage + path Frozen Logo

---

app/controllers/owner/equipments_controller.rb
app/views/owner/equipments/index.html.erb

Index des équipements d'un owner

Add Owner-list (Equipments-index)

---

app/assets/stylesheets/pages/_index.scss
app/controllers/owner/bookings_controller.rb
app/views/owner/bookings/index.html.erb

Ower bookings

---

.gitignore
app/views/equipments/index.html.erb
app/views/equipments/show.html.erb

Rajout de cl devant les image_tag pour éviter les problèmes d'hébergement d'images

Changement cloudinary

---

app/controllers/owner/bookings_controller.rb
app/views/owner/bookings/index.html.erb
db/migrate/20191127102338_change_default_value_status_to_bookings.rb
db/schema.rb

Changement des status d'une réservation:
- **p**ending
- accepted
- declined
En front:
- En attente (orange)
- Accepté (vert)
- Décliné (rouge)
Changement de la valeur par défault dans la DB: Pending => pending

Updated owner bookings page + default satus booking

---

app/controllers/equipments_controller.rb
app/views/bookings/index.html.erb
app/views/equipments/index.html.erb
dùfmlk

tri non proprio sur index equipement

---

app/controllers/owner/bookings_controller.rb
app/views/bookings/index.html.erb
app/views/owner/bookings/index.html.erb

bookings owner: only  onwer's demands
booking user ok
index equipment all but user/owner

bookings owner ok

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/equipments/show.html.erb

show de l'équipement OK en front

Front équipement show

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/pages/_owner-bookings-index.scss
app/views/equipments/index.html.erb
app/views/layouts/application.html.erb

police revue et espace pour searchbar

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_map.scss
app/views/equipments/show.html.erb

front show equipment

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_tables.scss
app/views/owner/bookings/index.html.erb
app/views/shared/_navbar.html.erb

cf titre
fonctionnalité ajoutée sur navbar
boutons decline accept remis dans tableau owner bookings

Add currentpage to Navbar & buttons decline accept ownerbookings

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/views/equipments/index.html.erb

banner avec searchbar designée
on verra demain pour peaufiner si besoin

Banner améliorée et searchbar

---

app/views/shared/_navbar.html.erb

Navbar version finale
Mise en valeur de la page active
Avatar espacé encore un peu plus

Navbar version finale

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Formulaires login, log-out, mot de passe oublié mis en forme.

Formulaires plus propres

---

app/views/bookings/index.html.erb
app/views/owner/bookings/index.html.erb
config/application.rb
config/locales/fr.yml
config/locales/simple_form.fr.yml

Dates au format français

---

config/locales/devise.fr.yml

Traductions OK

---

app/views/devise/confirmations/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/owner/equipments/new.html.erb

alignement couleur bouton "ajout equipment" et "se connecter"

couleur button se connecter & ajouter votre equipment

---

app/views/bookings/index.html.erb

Modifier text sous le bouton 'annuler la demande'

modifier text annuler
